-- =============================================================================
-- Seed: species table (~50 common plants for development)
-- =============================================================================

INSERT INTO species (common_name, scientific_name, family) VALUES
  ('Monstera deliciosa', 'Monstera deliciosa', 'Araceae'),
  ('Pothos', 'Epipremnum aureum', 'Araceae'),
  ('Ficus elastica', 'Ficus elastica', 'Moraceae'),
  ('Aloe vera', 'Aloe vera', 'Asphodelaceae'),
  ('Sansevieria', 'Dracaena trifasciata', 'Asparagaceae'),
  ('Philodendron', 'Philodendron hederaceum', 'Araceae'),
  ('Calathea', 'Calathea orbifolia', 'Marantaceae'),
  ('Tradescantia', 'Tradescantia zebrina', 'Commelinaceae'),
  ('Pilea peperomioides', 'Pilea peperomioides', 'Urticaceae'),
  ('Begonia', 'Begonia maculata', 'Begoniaceae'),
  ('Ceropegia', 'Ceropegia woodii', 'Apocynaceae'),
  ('Hoya', 'Hoya carnosa', 'Apocynaceae'),
  ('Alocasia', 'Alocasia amazonica', 'Araceae'),
  ('Syngonium', 'Syngonium podophyllum', 'Araceae'),
  ('Chlorophytum', 'Chlorophytum comosum', 'Asparagaceae'),
  ('Zamioculcas', 'Zamioculcas zamiifolia', 'Araceae'),
  ('Dracaena', 'Dracaena marginata', 'Asparagaceae'),
  ('Dieffenbachia', 'Dieffenbachia seguine', 'Araceae'),
  ('Maranta', 'Maranta leuconeura', 'Marantaceae'),
  ('Peperomia', 'Peperomia obtusifolia', 'Piperaceae'),
  ('Crassula', 'Crassula ovata', 'Crassulaceae'),
  ('Echeveria', 'Echeveria elegans', 'Crassulaceae'),
  ('Haworthia', 'Haworthiopsis attenuata', 'Asphodelaceae'),
  ('Kalanchoe', 'Kalanchoe blossfeldiana', 'Crassulaceae'),
  ('Sedum', 'Sedum morganianum', 'Crassulaceae'),
  ('Lavande', 'Lavandula angustifolia', 'Lamiaceae'),
  ('Romarin', 'Salvia rosmarinus', 'Lamiaceae'),
  ('Menthe', 'Mentha spicata', 'Lamiaceae'),
  ('Basilic', 'Ocimum basilicum', 'Lamiaceae'),
  ('Thym', 'Thymus vulgaris', 'Lamiaceae'),
  ('Sauge', 'Salvia officinalis', 'Lamiaceae'),
  ('Fraisier', 'Fragaria × ananassa', 'Rosaceae'),
  ('Tomate', 'Solanum lycopersicum', 'Solanaceae'),
  ('Piment', 'Capsicum annuum', 'Solanaceae'),
  ('Concombre', 'Cucumis sativus', 'Cucurbitaceae'),
  ('Rose', 'Rosa × hybrid', 'Rosaceae'),
  ('Hortensia', 'Hydrangea macrophylla', 'Hydrangeaceae'),
  ('Lierre', 'Hedera helix', 'Araliaceae'),
  ('Fougère de Boston', 'Nephrolepis exaltata', 'Nephrolepidaceae'),
  ('Anthurium', 'Anthurium andraeanum', 'Araceae'),
  ('Spathiphyllum', 'Spathiphyllum wallisii', 'Araceae'),
  ('Ficus lyrata', 'Ficus lyrata', 'Moraceae'),
  ('Strelitzia', 'Strelitzia nicolai', 'Strelitziaceae'),
  ('Agave', 'Agave americana', 'Asparagaceae'),
  ('Yucca', 'Yucca elephantipes', 'Asparagaceae'),
  ('Croton', 'Codiaeum variegatum', 'Euphorbiaceae'),
  ('Schefflera', 'Schefflera arboricola', 'Araliaceae'),
  ('Pachira', 'Pachira aquatica', 'Malvaceae'),
  ('Citronnier', 'Citrus limon', 'Rutaceae'),
  ('Olivier', 'Olea europaea', 'Oleaceae')
ON CONFLICT DO NOTHING;
